name: Derive Artifact Version

description: Derives artifact version using branch name and last release tag

outputs:
  artifact-version:
    description: New artifact version
    value: ${{ steps.create-artifact-version.outputs.artifact-version }}
  previous-version: 
    description: Semantically previous artifact version
    value: ${{ steps.create-artifact-version.outputs.pevious-version }}

runs:
  using: "composite"
  steps:
    - name: Create Artifact Version
      id: create-artifact-version
      env:
        BRANCH_NAME: ${{ github.ref_name }}
      shell: bash
      run: |
        echo "Branch Name - ${BRANCH_NAME}"

        if [[ "${BRANCH_NAME}" =~ release/v([0-9]+)\.([0-9]+) ]]; then

            MAJOR=${BASH_REMATCH[1]}
            MINOR=${BASH_REMATCH[2]}

            echo "Release Major - ${MAJOR}, Minor - ${MINOR}"

            LATEST_TAG=$(git tag --list "${MAJOR}.${MINOR}.*" --sort=-v:refname | head -n 1)

            if [ -z "${LATEST_TAG}" ]; then

                echo "No previous tag found. Starting from ${MAJOR}.${MINOR}.0"
                echo "artifact-version=${MAJOR}.${MINOR}.0" >> ${GITHUB_OUTPUT}

                if [ "${MINOR}" = "0" ]; then

                    LAST_MAJOR=$((${MAJOR} - 1))
                    LAST_VERSION=$(git tag --list "${LAST_MAJOR}.*.*" --sort=-v:refname | head -n 1)

                    echo "Last Artifact Tag found - ${LAST_VERSION}"
                    echo "pevious-version=${LAST_VERSION}" >> ${GITHUB_OUTPUT} 
                
                else
                    
                    LAST_MINOR=$((${MINOR} - 1))
                    LAST_VERSION=$(git tag --list "${MAJOR}.${LAST_MINOR}.*" --sort=-v:refname | head -n 1)
                    echo "pevious-version=${LAST_VERSION}" >> ${GITHUB_OUTPUT}
                fi

            else

                PATCH=$(echo "$LATEST_TAG" | awk -F. '{print $3}')
                echo "Current Patch - ${PATCH}"

                NEW_PATCH=$((${PATCH} + 1))

                echo "Found latest tag: ${LATEST_TAG}. Incrementing patch to ${NEW_PATCH}"

                echo "artifact-version=${MAJOR}.${MINOR}.${NEW_PATCH}" >> ${GITHUB_OUTPUT}
                echo "pevious-version=${LATEST_TAG}" >> ${GITHUB_OUTPUT}
            fi
        fi
