name: Build

on: 
    push:

jobs:
    prerequisites:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Create Artifact Version
              id: create-artifact-version
              env:
                BRANCH_NAME: ${{ github.ref_name }}
              run: |
                echo "Branch Name - ${BRANCH_NAME}"

                if [[ "${BRANCH_NAME}" =~ release/v([0-9]+)\.([0-9]+) ]]; then

                    MAJOR=${BASH_REMATCH[1]}
                    MINOR=${BASH_REMATCH[2]}

                    echo "Release Major - ${MAJOR}, Minor - ${MINOR}"

                    git tag --list

                    LATEST_TAG=$(git tag --list "${MAJOR}.${MINOR}.*" --sort=-v:refname | head -n 1)

                    if [ -z "${LATEST_TAG}" ]; then

                        echo "No previous tag found. Starting from ${MAJOR}.${MINOR}.0"
                        echo "artifact-version=${MAJOR}.${MINOR}.0" >> ${GITHUB_OUTPUT}

                        if [ "${MINOR}" = "0" ]; then

                            LAST_MAJOR=$((${MAJOR} - 1))
                            LAST_VERSION=$(git tag --list "${LAST_MAJOR}.*.*" --sort=-v:refname | head -n 1)

                            echo "Last Artifact Tag found - ${LAST_VERSION}"
                            echo "pevious-version=${LAST_VERSION}" >> ${GITHUB_OUTPUT} 
                        
                        else
                            
                            LAST_MINOR=$((${MINOR} - 1))
                            LAST_VERSION=$(git tag --list "${MAJOR}.${LAST_MINOR}.*" --sort=-v:refname | head -n 1)
                            echo "pevious-version=${LAST_VERSION}" >> ${GITHUB_OUTPUT}
                        fi

                    else

                        PATCH=$(echo "$LATEST_TAG" | awk -F. '{print $3}')
                        echo "Current Patch - ${PATCH}"

                        NEW_PATCH=$((${PATCH} + 1))

                        echo "Found latest tag: ${LATEST_TAG}. Incrementing patch to ${NEW_PATCH}"

                        echo "artifact-version=${MAJOR}.${MINOR}.${NEW_PATCH}" >> ${GITHUB_OUTPUT}
                        echo "pevious-version=${LATEST_TAG}" >> ${GITHUB_OUTPUT}
                    fi
                fi

            - name: Print Stuff
              env:
                ARTIFACT_VERSION: ${{ steps.create-artifact-version.outputs.artifact-version }}
                PREVIOUS_VERSION: ${{ steps.create-artifact-version.outputs.pevious-version }}
              run: |
                echo "Artifact Version - ${ARTIFACT_VERSION}"
                echo "Previous Version - ${PREVIOUS_VERSION}"
