name: Build

on: 
    push:
        branches:
            - release/v*

jobs:
    prerequisites:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Create Artifact Version
              id: create-artifact-version
              uses: ./version-setup

            - name: Print Stuff
              env:
                ARTIFACT_VERSION: ${{ steps.create-artifact-version.outputs.artifact-version }}
                PREVIOUS_VERSION: ${{ steps.create-artifact-version.outputs.pevious-version }}
              run: |
                echo "Artifact Version - ${ARTIFACT_VERSION}"
                echo "Previous Version - ${PREVIOUS_VERSION}"
