name: Build

on: 
    workflow_dispatch:

jobs:
    prerequisites:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Print Hello
              run: |
                echo "Hello Github Actions !"
